services:
  challenger-api:
    image: redteamsubnet61/ab_sniffer_v5:latest
    build:
      context: .
      platforms:
        - linux/amd64
    restart: unless-stopped
    platform: linux/amd64
    privileged: true
    ulimits:
      nofile: 32768
    environment:
      TERM: ${TERM:-xterm}
      TZ: UTC
      ABS_API_PORT: ${ABS_API_PORT:-10001}
      ABS_CHALLENGE_API_KEY: ${ABS_CHALLENGE_API_KEY:-challenge_api_key}
      ABS_CHALLENGE_VERIFICATION_API_KEY: ${ABS_CHALLENGE_VERIFICATION_API_KEY:-super_secure_api_key}
      ABS_CHALLENGE_VERIFICATION_ENDPOINT: ${ABS_CHALLENGE_VERIFICATION_ENDPOINT:-http://challenge_server:8000/api/v1/verify}
      ABS_CHALLENGE_VERIFICATION_STARTUP_URL: ${ABS_CHALLENGE_VERIFICATION_STARTUP_URL:-http://challenge_server:8000/start}
    env_file:
      - path: .env
        required: false
    volumes:
      - "api-logs:${ABS_API_LOGS_DIR:-/var/log/rest.rt-abs-challenger}"
      - "api-data:${ABS_API_DATA_DIR:-/var/lib/rest.rt-abs-challenger}"
    ports:
      - "${ABS_API_PORT:-10001}:${ABS_API_PORT:-10001}"
    tty: true


volumes:
  api-logs:
  api-data:
