services:
  miner-api:
    image: redteamsubnet61/rest.rt-abs-miner:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - 10002:10002
    environment:
      TERM: ${TERM:-xterm}
      TZ: UTC
      HBM_API_PORT: ${HBM_API_PORT:-8000}
    env_file:
      - path: .env
        required: false
    tty: true
    volumes:
      - "./src:/app"
