challenge:
  api_key: "challenge_api_key"
  docker_ulimit: 32768
  bot_timeout: 10
  repeated_framework_count: 3
  verification:
    endpoint: "http://challenge_server:8000/api/v1/verify"
    api_key: "super_secure_api_key"
    startup_url: "http://challenge_server:8000/start"
    extra: {}
  framework_images:
    - name: seleniumbase
      image: redteamsubnet61/seleniumbase@sha256:6528bddec31a31e4b8cd2a3940cf34d7697abb4356e02c44ad362eb899c751ed
    - name: seleniumdriverless
      image: redteamsubnet61/seleniumdriverless@sha256:9c62b6f0bffe9abaf25fdb36a65b78add7234b59b4cea73cec94916d2ce633b1
    - name: pydoll
      image: redteamsubnet61/pydoll@sha256:0b5e38418f58e4d70b27aab161d60d4f962050675a5c55c046353648cfe3bb88
    - name: patchright
      image: redteamsubnet61/patchright@sha256:c76f22447b3d25140b1410e01700fca301f27ea46fbfede98e145f36b11bc141
    - name: zendriver
      image: redteamsubnet61/zendriver@sha256:113f8eb73ae52c265f494099222d688a9061b51c7cb6bc84f659081a4b20a7a2
    - name: nodriver
      image: redteamsubnet61/nodriver@sha256:00ecd5aaf537133df48292d8f53783226494a06d5ceadba00e3d4514a5908757
    - name: botasaurus
      image: redteamsubnet61/botasaurus@sha256:ad6cb733ac8b0a5369ecb7b1c8eddc849e51570673050ef6bf453821510849ae
    - name: puppeteerextra
      image: redteamsubnet61/puppeteerextra@sha256:e358795bddad05cf3aa2f06d112aff729bbf2c803e936a6429fd7f55bea1aa4d
